
//Menu Items types
export const MENU_ITEMS_DOWNLOAD_START = 'MENU_ITEMS_DOWNLOAD_START';
export const MENU_ITEMS_DOWNLOAD_SUCCESS = 'MENU_ITEMS_DOWNLOAD_SUCCESS';
export const MENU_ITEMS_DOWNLOAD_ERROR = 'MENU_ITEMS_DOWNLOAD_ERROR';

//Slider Items types
export const SLIDER_ITEMS_DOWNLOAD_START = 'SLIDER_ITEMS_DOWNLOAD_START';
export const SLIDER_ITEMS_DOWNLOAD_SUCCESS = 'SLIDER_ITEMS_DOWNLOAD_SUCCESS';
export const SLIDER_ITEMS_DOWNLOAD_ERROR = 'SLIDER_ITEMS_DOWNLOAD_ERROR';

//Calculator Items types
export const CALCULATOR_ITEMS_DOWNLOAD_START = 'CALCULATOR_ITEMS_DOWNLOAD_START';
export const CALCULATOR_ITEMS_DOWNLOAD_SUCCESS = 'CALCULATOR_ITEMS_DOWNLOAD_SUCCESS';
export const CALCULATOR_ITEMS_DOWNLOAD_ERROR = 'CALCULATOR_ITEMS_DOWNLOAD_ERROR';

